on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: yehudat-c2a/test_git@master
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: docker build -t gta  .
      - name: run docker
        run: docker run --rm -it --entrypoint /bin/bash  gta:latest
